### ISSUE TITLE
Performance not as expected when trying to run

### ISSUE THREAD

**Issue by vladh** [BenSecret/CartPole#1]
Hi Ben!

I was trying to have a look at your solution, but when running it I get the following performance:

```
Episode 0       Average reward: nan
Episode 10      Average reward: 42.10
Episode 20      Average reward: 105.40
Episode 30      Average reward: 132.43
Episode 40      Average reward: 148.75
Episode 50      Average reward: 159.00
Episode 60      Average reward: 165.83
Episode 70      Average reward: 170.71
Episode 80      Average reward: 174.38
Episode 90      Average reward: 177.22
Episode 100     Average reward: 179.50
Completed at episode:  109
```

Do you have any idea why this could be? Thanks!

**Comment by BenSecret** [comment]
Hi Vladh!

Sorry for the slow reply. I get almost the same result – completing at 108, with the plot showing it's scoring the maximum reward from about episode 21 onwards.

Episode 0	Average reward: nan
Episode 10	Average reward: 42.10
Episode 20	Average reward: 105.70
Episode 30	Average reward: 137.13
Episode 40	Average reward: 152.85
Episode 50	Average reward: 162.28
Episode 60	Average reward: 168.57
Episode 70	Average reward: 173.06
Episode 80	Average reward: 176.43
Episode 90	Average reward: 179.04
Episode 100	Average reward: 181.14
Completed at episode:  108

I imagine the slight difference may be down to our systems' random number generation? The very low completion scores listed on the Leaderboards seem to be an ad-hoc standard of measuring the completion point via a moving average. I'm not sure where that came from, but I went with it as my example is (/was) still completing faster than the 2nd and 3rd places (but the leaderboards need much better regulation really, as many top scores are simply down to getting the right initial states to learn from).
